name: AspNetCore NuGet Push

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update AspNetCore NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v4     
        with:
            dotnet-version: '8.0.x'  

      - name: Build and Publish
        run: |  
          cd ./src/RedisRateLimiting.AspNetCore/
          dotnet pack -c Release -o artifacts -p:PackageVersion=1.2.0

      - name: Push
        run: dotnet nuget push ./src/RedisRateLimiting.AspNetCore/artifacts/RedisRateLimiting.AspNetCore.1.2.0.nupkg -k ${{ secrets.NUGET_APIKEY }} -s https://api.nuget.org/v3/index.json
